name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Extract version
        id: version
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          VERSION=$(echo "$GITHUB_REF" | sed 's|refs/tags/v||')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build:
    needs: setup
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            type: deb
            jpackage-args: --linux-shortcut
          - os: macos-latest
            type: dmg
            jpackage-args: --mac-package-name AndroidToolkit
          - os: windows-latest
            type: msi
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 25
          java-package: 'jdk+fx'

      - name: Set Maven version
        shell: bash
        run: mvn versions:set -DnewVersion="${{ needs.setup.outputs.version }}" -DgenerateBackupPoms=false

      - name: Build
        run: mvn package -DskipTests

      - name: Prepare JAR
        run: cp target/*.jar target/app.jar

      - name: jpackage (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          jpackage \
          --name AndroidToolkit \
          --input target \
          --main-jar app.jar \
          --main-class app.androidtoolkit.Launcher \
          --dest dist \
          --java-options "--enable-native-access=ALL-UNNAMED" \
          --type ${{ matrix.type }} \
          --app-version ${{ needs.setup.outputs.version }} \
          ${{ matrix.jpackage-args }}

      - name: jpackage (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          jpackage `
            --name AndroidToolkit `
            --input target `
            --main-jar app.jar `
            --main-class app.androidtoolkit.Launcher `
            --dest dist `
            --java-options "--enable-native-access=ALL-UNNAMED" `
            --type ${{ matrix.type }} `
            --app-version ${{ needs.setup.outputs.version }} `
            --win-dir-chooser `
            --win-per-user-install `
            --win-shortcut

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer-${{ matrix.os }}
          path: dist/*

  release:
    needs: [ setup, build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.setup.outputs.version }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: artifacts/**/*